cursor #f0dfd8
cursor_text_color #d7c2b9

foreground            #f0dfd8
background            #1a120e
selection_foreground  #000000
selection_background  #ffb74d
url_color             #ff6d00

color0   #1a120e
color1   #ff1d07
color2   #2cff00
color3   #ffd100
color4   #f26700
color5   #763200
color6   #ff6d00
color7   #ffede0
color8   #a5978c
color9   #ff493f
color10  #6bff4c
color11  #ffdf4c
color12  #ff8226
color13  #ff984c
color14  #ffbd8c
color15  #fff7f2
